name: CI

on:
  push:
    branches:
      - master

jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
        with:
          name: build
          path: build_production

  job2:
    name: Publish
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download job1 artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
          path: ./

      - name: Init git & set user
        run: |
          git init
          git config user.email "pujanpoudelj7@gmail.com"
          git config user.name "pujan poudel"

      - name: Git add & commit
        run: |
          git add .
          git commit -m "new changes"

      - name: Add remote & force push
        run: |
          git remote add origin git@github.com:pujanpoudel/portfolio.git
          git push -f origin master
